import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { client } from '@/utils/trpc'
import NavBar from '@/components/NavBar'

export default function Home() {

  const { data } = client.hello.useQuery({ text: 'Arjun ' })

  return (
    <>
      <Head>
        <title>tRPC | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main className = {inter.className}>
        <NavBar />
        <div className = ''>
          { data?.greeting }
        </div>
      </main>
    </>
  )
}
